@extends('layouts.admin')

@section('css')
    <link href="{{ asset('public/assets/plugins/datatable/dataTables.bootstrap4.min.css') }}" rel="stylesheet" />
    <link href="https://cdn.datatables.net/buttons/1.7.0/css/buttons.dataTables.min.css" rel="stylesheet" />
    <link href="{{ asset('public/assets/plugins/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet" />

@endsection
@section('title') Labortory Report @endsection

@section('content')
<form method="get" action="{{url('filter-lab-report')}}">
    <div class="card p-3">
        <div class="row">
            <div class="col-md-6">
                <h4>Date</h4>
                <div class="btn-list">
                        <div class="input-group">
                            <div class="input-group-text">
                                <i class="fa fa-calendar"></i>
                            </div>
                           <input type="text" class="form-control pull-right" name="date" id="reservation" required>
                           <button type="submit" class="btn btn-success">Filter</button>

                    </div>
                </div>
            </div>
  
        </div>
        <div class=" text-right">
        </div>
    </form>


        <div class="mt-5 tables table-responsive">
            <table class="table table-striped table-bordered table-sm text-nowrap w-100 dataTable no-footer table-main"
                id="example">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Bill Number</th>
                        <th>Payment Type</th>
                        <th>Type</th>
                        <th>Description</th>
                        <th>Total Amount</th>
                        <th>Generated By</th>
                        <th>status</th>
                        <th>Issue Date</th>
                    </tr>
                </thead>
                <tbody>
                    @php $t=""; $counter=1; @endphp
                    @if(!empty($ph))
                    @foreach ($ph as $row)
             
                        <tr id="">
                            <td>{{ $counter++ }}</td>
                            <td>@php 
                                $bill=Helper::getbillnumberforlab($row->bill_id);
                            @endphp {{$bill}}</td>

                            <td>{{ $row->payment_type }}</td>
                            <td>
                                @if($row->type=="Expense")
                                <span class="badge badge-danger">{{$row->type}}</span>
                                @else
                                <span class="badge badge-success">Income</span>
                                @endif
                            </td>
                            <td>@if(!empty($row->description)) {{$row->description}} @else N/A @endif</td>
                            <td>{{ $row->total }}</td>
                            <td>{{ $row->email }}</td>
                            <td>{{ $row->status }}</td>
                            <td>{{ $row->created_at }}</td>
                        </tr>
                        @php   $t= (int)$t+(int)$row->total @endphp
                    @endforeach

    
                    <tfoot>
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th>Total Income</th>
                            <th>{{$t}}</th>
                        </tr>
                    </tfoot>
                    @endif
                </tbody>
            </table>
      
        </div>
    </div>
@endsection

@section('directory')
<li class="breadcrumb-item active" aria-current="page">Report</li>
<li class="breadcrumb-item active" aria-current="page">Laboratory</li>
@endsection

@section('jquery')
    <script src="{{ asset('public/assets/plugins/datatable/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('public/assets/plugins/datatable/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('public/assets/plugins/datatable/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('public/assets/plugins/bootstrap-daterangepicker/daterangepicker.js') }}"></script>

    <script src="{{ asset('public/assets/plugins/bootstrap-daterangepicker/moment.min.js') }}"></script>

    <script src="https://cdn.datatables.net/buttons/1.7.0/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.0/js/buttons.print.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.0/js/buttons.html5.min.js"></script>

    <script>
        	$('#reservation').daterangepicker();
        $('#example').DataTable({
            dom: 'Blfrtip',
            "bLengthChange": false,
            "pageLength": 50,
            'paging':false,
            buttons: [{
                    extend: 'pdf',
                    footer: true,
                    customize: function(doc) {
                        doc.defaultStyle.fontSize = 8;
                        doc.defaultStyle.width = "100%";

                    },
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4, 5, 6,7,8],
                    }
                },
                {
                    extend: 'print',
                    footer: true,
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4, 5, 6,7,8]
                    }
                },

            ],
        });
        $('.buttons-print, .buttons-pdf ,.buttons-colvis').addClass('btn btn-primary mr-1');
    </script>

@endsection
